/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedStudioRouteRouteImport } from './routes/_authenticated/studio/route'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio/index'
import { Route as AuthenticatedStudioAssetsRouteImport } from './routes/_authenticated/studio/assets'
import { Route as AuthenticatedStudioCustomersRouteImport } from './routes/_authenticated/studio/customers'
import { Route as AuthenticatedStudioIntegrationsRouteImport } from './routes/_authenticated/studio/integrations'
import { Route as AuthenticatedStudioLibraryRouteImport } from './routes/_authenticated/studio/library'
import { Route as AuthenticatedStudioLinkedinRouteImport } from './routes/_authenticated/studio/linkedin'
import { Route as AuthenticatedStudioMediaRouteImport } from './routes/_authenticated/studio/media'
import { Route as AuthenticatedStudioNewRouteImport } from './routes/_authenticated/studio/new'
import { Route as AuthenticatedStudioPromptsRouteImport } from './routes/_authenticated/studio/prompts'
import { Route as AuthenticatedStudioQaRouteImport } from './routes/_authenticated/studio/qa'
import { Route as AuthenticatedStudioScheduleRouteImport } from './routes/_authenticated/studio/schedule'
import { Route as AuthenticatedStudioSettingsRouteImport } from './routes/_authenticated/studio/settings'
import { Route as AuthenticatedStudioSocialRouteImport } from './routes/_authenticated/studio/social'
import { Route as AuthenticatedStudioProjectIdRouteImport } from './routes/_authenticated/studio/project.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRouteRoute =
  AuthenticatedStudioRouteRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioAssetsRoute =
  AuthenticatedStudioAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioCustomersRoute =
  AuthenticatedStudioCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioIntegrationsRoute =
  AuthenticatedStudioIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioLibraryRoute =
  AuthenticatedStudioLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioLinkedinRoute =
  AuthenticatedStudioLinkedinRouteImport.update({
    id: '/linkedin',
    path: '/linkedin',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioMediaRoute =
  AuthenticatedStudioMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioNewRoute = AuthenticatedStudioNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedStudioRouteRoute,
} as any)
const AuthenticatedStudioPromptsRoute =
  AuthenticatedStudioPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioQaRoute = AuthenticatedStudioQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AuthenticatedStudioRouteRoute,
} as any)
const AuthenticatedStudioScheduleRoute =
  AuthenticatedStudioScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioSettingsRoute =
  AuthenticatedStudioSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioSocialRoute =
  AuthenticatedStudioSocialRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioProjectIdRoute =
  AuthenticatedStudioProjectIdRouteImport.update({
    id: '/project/$id',
    path: '/project/$id',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof AuthenticatedStudioRouteRouteWithChildren
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/studio/assets': typeof AuthenticatedStudioAssetsRoute
  '/studio/customers': typeof AuthenticatedStudioCustomersRoute
  '/studio/integrations': typeof AuthenticatedStudioIntegrationsRoute
  '/studio/library': typeof AuthenticatedStudioLibraryRoute
  '/studio/linkedin': typeof AuthenticatedStudioLinkedinRoute
  '/studio/media': typeof AuthenticatedStudioMediaRoute
  '/studio/new': typeof AuthenticatedStudioNewRoute
  '/studio/prompts': typeof AuthenticatedStudioPromptsRoute
  '/studio/qa': typeof AuthenticatedStudioQaRoute
  '/studio/schedule': typeof AuthenticatedStudioScheduleRoute
  '/studio/settings': typeof AuthenticatedStudioSettingsRoute
  '/studio/social': typeof AuthenticatedStudioSocialRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/studio/project/$id': typeof AuthenticatedStudioProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/studio/assets': typeof AuthenticatedStudioAssetsRoute
  '/studio/customers': typeof AuthenticatedStudioCustomersRoute
  '/studio/integrations': typeof AuthenticatedStudioIntegrationsRoute
  '/studio/library': typeof AuthenticatedStudioLibraryRoute
  '/studio/linkedin': typeof AuthenticatedStudioLinkedinRoute
  '/studio/media': typeof AuthenticatedStudioMediaRoute
  '/studio/new': typeof AuthenticatedStudioNewRoute
  '/studio/prompts': typeof AuthenticatedStudioPromptsRoute
  '/studio/qa': typeof AuthenticatedStudioQaRoute
  '/studio/schedule': typeof AuthenticatedStudioScheduleRoute
  '/studio/settings': typeof AuthenticatedStudioSettingsRoute
  '/studio/social': typeof AuthenticatedStudioSocialRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/studio/project/$id': typeof AuthenticatedStudioProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRouteRouteWithChildren
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/_authenticated/studio/assets': typeof AuthenticatedStudioAssetsRoute
  '/_authenticated/studio/customers': typeof AuthenticatedStudioCustomersRoute
  '/_authenticated/studio/integrations': typeof AuthenticatedStudioIntegrationsRoute
  '/_authenticated/studio/library': typeof AuthenticatedStudioLibraryRoute
  '/_authenticated/studio/linkedin': typeof AuthenticatedStudioLinkedinRoute
  '/_authenticated/studio/media': typeof AuthenticatedStudioMediaRoute
  '/_authenticated/studio/new': typeof AuthenticatedStudioNewRoute
  '/_authenticated/studio/prompts': typeof AuthenticatedStudioPromptsRoute
  '/_authenticated/studio/qa': typeof AuthenticatedStudioQaRoute
  '/_authenticated/studio/schedule': typeof AuthenticatedStudioScheduleRoute
  '/_authenticated/studio/settings': typeof AuthenticatedStudioSettingsRoute
  '/_authenticated/studio/social': typeof AuthenticatedStudioSocialRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/_authenticated/studio/project/$id': typeof AuthenticatedStudioProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/studio'
    | '/api/generate-image'
    | '/studio/assets'
    | '/studio/customers'
    | '/studio/integrations'
    | '/studio/library'
    | '/studio/linkedin'
    | '/studio/media'
    | '/studio/new'
    | '/studio/prompts'
    | '/studio/qa'
    | '/studio/schedule'
    | '/studio/settings'
    | '/studio/social'
    | '/studio/'
    | '/studio/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/generate-image'
    | '/studio/assets'
    | '/studio/customers'
    | '/studio/integrations'
    | '/studio/library'
    | '/studio/linkedin'
    | '/studio/media'
    | '/studio/new'
    | '/studio/prompts'
    | '/studio/qa'
    | '/studio/schedule'
    | '/studio/settings'
    | '/studio/social'
    | '/studio'
    | '/studio/project/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/studio'
    | '/api/generate-image'
    | '/_authenticated/studio/assets'
    | '/_authenticated/studio/customers'
    | '/_authenticated/studio/integrations'
    | '/_authenticated/studio/library'
    | '/_authenticated/studio/linkedin'
    | '/_authenticated/studio/media'
    | '/_authenticated/studio/new'
    | '/_authenticated/studio/prompts'
    | '/_authenticated/studio/qa'
    | '/_authenticated/studio/schedule'
    | '/_authenticated/studio/settings'
    | '/_authenticated/studio/social'
    | '/_authenticated/studio/'
    | '/_authenticated/studio/project/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/assets': {
      id: '/_authenticated/studio/assets'
      path: '/assets'
      fullPath: '/studio/assets'
      preLoaderRoute: typeof AuthenticatedStudioAssetsRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/customers': {
      id: '/_authenticated/studio/customers'
      path: '/customers'
      fullPath: '/studio/customers'
      preLoaderRoute: typeof AuthenticatedStudioCustomersRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/integrations': {
      id: '/_authenticated/studio/integrations'
      path: '/integrations'
      fullPath: '/studio/integrations'
      preLoaderRoute: typeof AuthenticatedStudioIntegrationsRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/library': {
      id: '/_authenticated/studio/library'
      path: '/library'
      fullPath: '/studio/library'
      preLoaderRoute: typeof AuthenticatedStudioLibraryRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/linkedin': {
      id: '/_authenticated/studio/linkedin'
      path: '/linkedin'
      fullPath: '/studio/linkedin'
      preLoaderRoute: typeof AuthenticatedStudioLinkedinRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/media': {
      id: '/_authenticated/studio/media'
      path: '/media'
      fullPath: '/studio/media'
      preLoaderRoute: typeof AuthenticatedStudioMediaRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/new': {
      id: '/_authenticated/studio/new'
      path: '/new'
      fullPath: '/studio/new'
      preLoaderRoute: typeof AuthenticatedStudioNewRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/prompts': {
      id: '/_authenticated/studio/prompts'
      path: '/prompts'
      fullPath: '/studio/prompts'
      preLoaderRoute: typeof AuthenticatedStudioPromptsRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/qa': {
      id: '/_authenticated/studio/qa'
      path: '/qa'
      fullPath: '/studio/qa'
      preLoaderRoute: typeof AuthenticatedStudioQaRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/schedule': {
      id: '/_authenticated/studio/schedule'
      path: '/schedule'
      fullPath: '/studio/schedule'
      preLoaderRoute: typeof AuthenticatedStudioScheduleRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/settings': {
      id: '/_authenticated/studio/settings'
      path: '/settings'
      fullPath: '/studio/settings'
      preLoaderRoute: typeof AuthenticatedStudioSettingsRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/social': {
      id: '/_authenticated/studio/social'
      path: '/social'
      fullPath: '/studio/social'
      preLoaderRoute: typeof AuthenticatedStudioSocialRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/project/$id': {
      id: '/_authenticated/studio/project/$id'
      path: '/project/$id'
      fullPath: '/studio/project/$id'
      preLoaderRoute: typeof AuthenticatedStudioProjectIdRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
  }
}

interface AuthenticatedStudioRouteRouteChildren {
  AuthenticatedStudioAssetsRoute: typeof AuthenticatedStudioAssetsRoute
  AuthenticatedStudioCustomersRoute: typeof AuthenticatedStudioCustomersRoute
  AuthenticatedStudioIntegrationsRoute: typeof AuthenticatedStudioIntegrationsRoute
  AuthenticatedStudioLibraryRoute: typeof AuthenticatedStudioLibraryRoute
  AuthenticatedStudioLinkedinRoute: typeof AuthenticatedStudioLinkedinRoute
  AuthenticatedStudioMediaRoute: typeof AuthenticatedStudioMediaRoute
  AuthenticatedStudioNewRoute: typeof AuthenticatedStudioNewRoute
  AuthenticatedStudioPromptsRoute: typeof AuthenticatedStudioPromptsRoute
  AuthenticatedStudioQaRoute: typeof AuthenticatedStudioQaRoute
  AuthenticatedStudioScheduleRoute: typeof AuthenticatedStudioScheduleRoute
  AuthenticatedStudioSettingsRoute: typeof AuthenticatedStudioSettingsRoute
  AuthenticatedStudioSocialRoute: typeof AuthenticatedStudioSocialRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
  AuthenticatedStudioProjectIdRoute: typeof AuthenticatedStudioProjectIdRoute
}

const AuthenticatedStudioRouteRouteChildren: AuthenticatedStudioRouteRouteChildren =
  {
    AuthenticatedStudioAssetsRoute: AuthenticatedStudioAssetsRoute,
    AuthenticatedStudioCustomersRoute: AuthenticatedStudioCustomersRoute,
    AuthenticatedStudioIntegrationsRoute: AuthenticatedStudioIntegrationsRoute,
    AuthenticatedStudioLibraryRoute: AuthenticatedStudioLibraryRoute,
    AuthenticatedStudioLinkedinRoute: AuthenticatedStudioLinkedinRoute,
    AuthenticatedStudioMediaRoute: AuthenticatedStudioMediaRoute,
    AuthenticatedStudioNewRoute: AuthenticatedStudioNewRoute,
    AuthenticatedStudioPromptsRoute: AuthenticatedStudioPromptsRoute,
    AuthenticatedStudioQaRoute: AuthenticatedStudioQaRoute,
    AuthenticatedStudioScheduleRoute: AuthenticatedStudioScheduleRoute,
    AuthenticatedStudioSettingsRoute: AuthenticatedStudioSettingsRoute,
    AuthenticatedStudioSocialRoute: AuthenticatedStudioSocialRoute,
    AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
    AuthenticatedStudioProjectIdRoute: AuthenticatedStudioProjectIdRoute,
  }

const AuthenticatedStudioRouteRouteWithChildren =
  AuthenticatedStudioRouteRoute._addFileChildren(
    AuthenticatedStudioRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudioRouteRoute: typeof AuthenticatedStudioRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudioRouteRoute: AuthenticatedStudioRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
