-- ParkKey LinkedIn autumn series, 2026-09-16 through 2026-10-02.
-- Truth rule: this migration creates an editorial schedule only.
-- It never marks a post PUBLISHED and never fabricates LinkedIn post URLs.
-- Asset rows below are creative briefs with no storage_path until a real approved file is attached.

INSERT INTO public.media_assets
  (id, name, kind, category, mime_type, storage_path, tags, usage_rights, source_notes, approval_status, campaign, notes)
VALUES
  ('a1600000-0000-4000-8000-000000000001', 'Höstserie 01 — Ingen ny app', 'image-brief', 'social', NULL, NULL,
   ARRAY['linkedin','autumn-2026','existing-app','no-new-app'], 'ParkKey-owned creative brief',
   'Create with approved ParkKey logo and canonical Parky only. Nordic cinematic city, existing mobility app visually primary.',
   'PLANNED — ASSET REQUIRED', 'LinkedIn Höstserie 2026', 'Target format 4:5. No partner logo unless separately approved.'),
  ('a1600000-0000-4000-8000-000000000002', 'Höstserie 02 — Belöningen gör dagen', 'image-brief', 'social', NULL, NULL,
   ARRAY['linkedin','autumn-2026','parky','reward'], 'ParkKey-owned creative brief',
   'Canonical Parky in a warm Nordic autumn mobility moment. Human-first, premium, realistic, no redesign of Parky.',
   'PLANNED — ASSET REQUIRED', 'LinkedIn Höstserie 2026', 'Target format 4:5. Reward moment, not discount-spam aesthetics.'),
  ('a1600000-0000-4000-8000-000000000003', 'Höstserie 03 — Från parkering till beteende', 'image-brief', 'social', NULL, NULL,
   ARRAY['linkedin','autumn-2026','parking','behaviour'], 'ParkKey-owned creative brief',
   'Cinematic before/after flow: verified parking event to rewarded next behaviour. Existing parking app remains primary.',
   'PLANNED — ASSET REQUIRED', 'LinkedIn Höstserie 2026', 'Target format 4:5. Do not imply a live named operator integration.'),
  ('a1600000-0000-4000-8000-000000000004', 'Höstserie 04 — Lokalt värde', 'image-brief', 'social', NULL, NULL,
   ARRAY['linkedin','autumn-2026','local-commerce','reward'], 'ParkKey-owned creative brief',
   'Nordic town centre, person receiving a verified reward and redeeming local value at an independent café/shop.',
   'PLANNED — ASSET REQUIRED', 'LinkedIn Höstserie 2026', 'Target format 4:5. No invented merchant logo.'),
  ('a1600000-0000-4000-8000-000000000005', 'Höstserie 05 — Låg-risk pilot', 'image-brief', 'social', NULL, NULL,
   ARRAY['linkedin','autumn-2026','municipality','pilot'], 'ParkKey-owned creative brief',
   'Public-sector appropriate Nordic city scene with a simple pilot path: existing system, selected behaviour, reward, measurable KPI.',
   'PLANNED — ASSET REQUIRED', 'LinkedIn Höstserie 2026', 'Target format 4:5. No unverified ROI or CO2 claims.'),
  ('a1600000-0000-4000-8000-000000000006', 'Höstserie 06 — Samma app mer värde', 'image-brief', 'social', NULL, NULL,
   ARRAY['linkedin','autumn-2026','mobility-operator','existing-app'], 'ParkKey-owned creative brief',
   'Premium operator-style mobility UI inside phone, ParkKey reward layer added after verified event, host brand concept stays primary.',
   'PLANNED — ASSET REQUIRED', 'LinkedIn Höstserie 2026', 'Target format 4:5. Use fictional/generic operator UI unless approved partner asset exists.'),
  ('a1600000-0000-4000-8000-000000000007', 'Höstserie 07 — CoreOS mätbarhet', 'image-brief', 'social', NULL, NULL,
   ARRAY['linkedin','autumn-2026','coreos','measurement'], 'ParkKey-owned creative brief',
   'Cinematic city plus restrained CoreOS proof layer showing verified events, KPI structure and follow-up without fabricated values.',
   'PLANNED — ASSET REQUIRED', 'LinkedIn Höstserie 2026', 'Target format 4:5. Any numbers must be labelled EXAMPLE/TARGET unless verified.'),
  ('a1600000-0000-4000-8000-000000000008', 'Höstserie 08 — Pilotinbjudan', 'image-brief', 'social', NULL, NULL,
   ARRAY['linkedin','autumn-2026','pilot','cta'], 'ParkKey-owned creative brief',
   'Warm Nordic city closing visual with canonical Parky, ParkKey logo and one clear pilot CTA.',
   'PLANNED — ASSET REQUIRED', 'LinkedIn Höstserie 2026', 'Target format 4:5. One CTA only: parkkey.org / dialogue invitation.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.social_posts
  (id, title, network, objective, audience, campaign, channel, aspect_ratio, cta, utm,
   copy_sv, copy_en, headline, overlay_copy, copy_direction, parky_usage, cinematic_mood,
   image_references, image_prompt, negative_prompt, alt_text, claim_check, crop_presets,
   status, truth_label, tags)
VALUES
  ('b1600000-0000-4000-8000-000000000001', '16/9 — Ingen ny app. Bara belöningen.', 'linkedin',
   'Position ParkKey as a reward layer inside systems people already use.', 'Municipalities, mobility operators, property and place leaders',
   'LinkedIn Höstserie 2026', 'linkedin', '4:5', 'Läs mer på parkkey.org',
   'utm_source=linkedin&utm_medium=organic&utm_campaign=autumn_2026&utm_content=no_new_app',
   E'Det behövs inte alltid ännu en app.\n\nParkKey™ är byggt för motsatsen: ett belönings- och beteendelager bakom de system människor redan använder.\n\nEn verifierad händelse kan bli nästa positiva beteende — parkering, kollektivtrafik, gång, cykel eller lokal aktivitet — utan att ta över kundresan.\n\nIngen ny app. Bara belöningen.\n\nVi söker nu fler aktörer som vill testa en smal, mätbar pilot.\n\n#ParkKey #Mobility #SmartCity #BehaviorChange',
   E'You do not always need another app.\n\nParkKey™ is designed as a reward and behaviour layer behind systems people already use.\n\nNo new app. Just the reward.',
   'Ingen ny app. Bara belöningen.', 'BEFINTLIG APP + PARKKEY™',
   'Lead with simplicity, distribution advantage and a measurable pilot.', 'Canonical Parky may appear as a supporting guide, never redesigned.',
   'Cinematic Nordic autumn city, premium realistic mobility scene, warm human activity.',
   'Approved ParkKey logo; canonical Parky reference; generic existing mobility app UI.',
   'Vertical 4:5 LinkedIn key art, cinematic Nordic autumn city at golden hour, real person using an existing mobility app on phone, subtle ParkKey reward layer appears after a verified mobility event, canonical Parky exactly as approved, premium photography, dark teal/turquoise ParkKey accents, readable minimal overlay: "Ingen ny app. Bara belöningen."',
   'No fake partner logos, no redesigned Parky, no pseudo-text, no invented statistics, no futuristic hologram overload.',
   'Person i nordisk höststad använder en befintlig mobilitetsapp medan ParkKey-belöningen visas som nästa lager.',
   'No numerical performance claim. Product-positioning statement only.', ARRAY['1:1','4:5','16:9','9:16'],
   'SCHEDULED — CONNECTION REQUIRED', 'PROPOSED', ARRAY['linkedin','autumn-2026','existing-app']),

  ('b1600000-0000-4000-8000-000000000002', '18/9 — Belöningen gör dagen', 'linkedin',
   'Make the reward moment human and memorable.', 'Municipalities, mobility operators, local commerce',
   'LinkedIn Höstserie 2026', 'linkedin', '4:5', 'Testa Parky-testet på parkkey.org',
   'utm_source=linkedin&utm_medium=organic&utm_campaign=autumn_2026&utm_content=reward_moment',
   E'Beteendeförändring börjar sällan med en dashboard. Den börjar med en människa.\n\nEtt litet positivt ögonblick kan göra stor skillnad: du gör något bra — och får något tillbaka direkt.\n\nDet är där Parky™ kommer in. ParkKey kopplar verifierade händelser till belöningar som känns relevanta i vardagen och kan skapa värde både för individen och lokalt.\n\nBelöningen gör dagen. Data visar om beteendet faktiskt förändras.\n\n#ParkKey #Parky #Rewards #Mobility',
   E'Behaviour change rarely starts with a dashboard. It starts with a person.\n\nA small positive reward moment can make a real difference.',
   'Belöningen gör dagen.', 'GÖR NÅGOT BRA → FÅ NÅGOT TILLBAKA',
   'Human-first story; reward before technology.', 'Canonical Parky is central but must match approved reference exactly.',
   'Warm Nordic autumn, genuine smile, realistic city movement, cinematic shallow depth of field.',
   'Canonical Parky; approved ParkKey logo; autumn city; reward moment.',
   'Vertical 4:5 cinematic Nordic autumn street, person has just completed a positive mobility action, canonical Parky exactly as approved appears as a warm reward guide, authentic human expression, premium advertising photography, ParkKey teal/lime accents, minimal overlay: "Belöningen gör dagen."',
   'No mascot redesign, no childish cartoon city, no fake coupons, no fake partner logos, no unverified numbers.',
   'Varm vardagsscen där Parky markerar ett positivt belöningsögonblick efter en verifierad aktivitet.',
   'Conceptual brand message; no quantified outcome claim.', ARRAY['1:1','4:5','16:9','9:16'],
   'SCHEDULED — CONNECTION REQUIRED', 'PROPOSED', ARRAY['linkedin','autumn-2026','parky','reward']),

  ('b1600000-0000-4000-8000-000000000003', '21/9 — Från parkeringshändelse till beteendeförändring', 'linkedin',
   'Explain the event-to-behaviour logic for parking partners.', 'Parking operators, municipalities, property owners',
   'LinkedIn Höstserie 2026', 'linkedin', '4:5', 'Prata pilot med oss via parkkey.org',
   'utm_source=linkedin&utm_medium=organic&utm_campaign=autumn_2026&utm_content=parking_event',
   E'Parkeringen är inte slutet på resan. Den kan vara startpunkten för nästa beteende.\n\nParkKey™ kan använda en verifierad parkeringshändelse som signal och lägga ett belöningslager efteråt: gå vidare till centrum, välja kollektivtrafik nästa gång, upptäcka lokal handel eller delta i en definierad aktivitet.\n\nParkeringsappen fortsätter vara parkeringsupplevelsen. ParkKey skapar nästa värde.\n\nOch piloten kan mätas med ett fåtal tydliga KPI:er.\n\n#Parking #ParkKey #Mobility #BehaviorChange',
   E'Parking does not have to be the end of the journey. It can trigger the next rewarded behaviour.',
   'Från parkering till nästa beteende.', 'VERIFIERAD HÄNDELSE → NÄSTA VÄRDE',
   'Show event verification, then reward, then next behaviour.', 'Parky supports the reward moment only.',
   'Premium Nordic parking-to-city transition, cinematic but credible.',
   'Generic parking app UI; canonical Parky; city/local commerce continuation.',
   'Vertical 4:5 split-flow cinematic image: car parked in Nordic city, existing parking app confirms session, subtle verified-event marker transitions into walking/local city activity and a ParkKey reward moment, canonical Parky exact reference, premium realistic photography.',
   'No named operator logo, no claim of live integration, no fake analytics, no redesigned mascot.',
   'Verifierad parkeringshändelse följs av en ParkKey-belöning och nästa aktivitet i staden.',
   'Use generic operator context unless a named partner has approved co-branding.', ARRAY['1:1','4:5','16:9','9:16'],
   'SCHEDULED — CONNECTION REQUIRED', 'PROPOSED', ARRAY['linkedin','autumn-2026','parking','behaviour']),

  ('b1600000-0000-4000-8000-000000000004', '23/9 — Belöningen kan stanna lokalt', 'linkedin',
   'Connect mobility rewards to local economic value.', 'Municipalities, destination organisations, local commerce',
   'LinkedIn Höstserie 2026', 'linkedin', '4:5', 'Utforska en lokal reward-pool pilot med ParkKey',
   'utm_source=linkedin&utm_medium=organic&utm_campaign=autumn_2026&utm_content=local_value',
   E'En belöning behöver inte lämna platsen där beteendet sker.\n\nTänk en verifierad aktivitet som leder till ett lokalt värde: kaffe, kultur, handel, föreningsstöd eller en annan relevant förmån.\n\nFör kommunen eller destinationen betyder det att beteendeförändring och lokal nytta kan byggas ihop i samma pilot.\n\nParkKey™ kan vara lagret som binder samman händelsen, belöningen och uppföljningen.\n\n#LocalCommerce #PlaceMaking #ParkKey #Rewards',
   E'A reward can stay local — connecting a verified activity with local commerce and community value.',
   'Belöningen kan stanna lokalt.', 'BETEENDE → BELÖNING → LOKALT VÄRDE',
   'Show tangible local redemption without discount-spam aesthetics.', 'Parky may guide the transition from event to local reward.',
   'Nordic town centre, warm autumn storefronts, local human activity.',
   'Independent café/shop without visible brand; canonical Parky; ParkKey reward cue.',
   'Vertical 4:5 cinematic Nordic town centre, person walking from mobility stop to independent local café, subtle ParkKey reward on phone, canonical Parky exact reference, warm autumn atmosphere, premium realistic photography, overlay: "Belöningen kan stanna lokalt."',
   'No invented merchant identity, no fake discount percentage, no generic coupon clutter.',
   'Person använder en ParkKey-belöning i lokal handel efter en verifierad aktivitet.',
   'Examples are illustrative; no claim that a named merchant is live.', ARRAY['1:1','4:5','16:9','9:16'],
   'SCHEDULED — CONNECTION REQUIRED', 'PROPOSED', ARRAY['linkedin','autumn-2026','local-commerce']),

  ('b1600000-0000-4000-8000-000000000005', '25/9 — Börja med en smal pilot', 'linkedin',
   'Lower perceived adoption risk for public-sector and partner pilots.', 'Municipal decision-makers and mobility partners',
   'LinkedIn Höstserie 2026', 'linkedin', '4:5', 'Boka ett kort pilot-fit samtal via parkkey.org',
   'utm_source=linkedin&utm_medium=organic&utm_campaign=autumn_2026&utm_content=pilot',
   E'Ni behöver inte börja stort.\n\nEn bra ParkKey™-pilot kan börja med:\n• ett tydligt beteende\n• en befintlig digital ingång\n• en enkel belöning\n• 2–4 KPI:er\n• en avgränsad period\n\nDet gör det möjligt att testa värdet innan man skalar.\n\nMålet är inte fler funktioner. Målet är ett mätbart svar på frågan: förändrar belöningen beteendet?\n\n#Pilot #Municipality #Mobility #ParkKey',
   E'Start narrow: one behaviour, one existing digital entry, one reward logic and a few measurable KPIs.',
   'Börja med en smal pilot.', 'LÅG RISK. TYDLIGT TEST. MÄTBART SVAR.',
   'Public-sector credible, structured, low-risk.', 'Parky is optional and secondary.',
   'Cinematic Nordic civic environment with restrained proof/KPI graphic layer.',
   'Generic municipality scene; ParkKey brand; pilot steps; no partner logo.',
   'Vertical 4:5 premium Nordic civic scene, simple five-step pilot path integrated subtly into the composition, real people in mobility context, ParkKey visual language, restrained data/proof accents, overlay: "Börja med en smal pilot."',
   'No unverified ROI, CO2 or participation numbers, no bureaucratic stock-photo look.',
   'Nordisk stadsmiljö med en enkel visualisering av en avgränsad ParkKey-pilot.',
   'All KPI references are framework examples, not achieved results.', ARRAY['1:1','4:5','16:9','9:16'],
   'SCHEDULED — CONNECTION REQUIRED', 'PROPOSED', ARRAY['linkedin','autumn-2026','municipality','pilot']),

  ('b1600000-0000-4000-8000-000000000006', '28/9 — Samma app. Mer värde.', 'linkedin',
   'Clarify operator positioning: ParkKey adds value without replacing the host app.', 'Mobility and parking operators',
   'LinkedIn Höstserie 2026', 'linkedin', '4:5', 'Se hur ParkKey kan ligga bakom er befintliga kundresa',
   'utm_source=linkedin&utm_medium=organic&utm_campaign=autumn_2026&utm_content=same_app',
   E'För en mobilitetsoperatör ska ParkKey™ inte bli ännu ett system som konkurrerar om kunden.\n\nVår utgångspunkt är enklare:\n\nOperatörens app fortsätter äga kundresan.\nDen verifierade händelsen finns redan.\nParkKey lägger till belöningen och beteendelogiken efteråt.\n\nSamma app. Mer värde.\n\nDet är den integrationsprincip vi vill testa tillsammans med fler operatörer.\n\n#MobilityOperator #Parking #PublicTransport #ParkKey',
   E'The operator keeps the customer journey. ParkKey adds the reward and behaviour layer after the verified event. Same app. More value.',
   'Samma app. Mer värde.', 'SAME APP. MORE VALUE.',
   'Operator brand concept visually primary; ParkKey is the added layer.', 'Parky only if it helps explain reward, not as dominant mascot.',
   'Premium realistic mobility app close-up in Nordic city.',
   'Generic operator app; ParkKey reward layer; no named partner unless approved.',
   'Vertical 4:5 premium mobility advertising image, phone showing a clean generic operator app in normal use, then a subtle ParkKey reward layer after verified event, Nordic city background, cinematic realistic lighting, overlay: "Samma app. Mer värde."',
   'No fake operator brand, no claim of production integration, no redesigned Parky.',
   'Befintlig mobilitetsapp är huvudupplevelsen medan ParkKey lägger till ett belöningslager.',
   'Conceptual integration principle; named integrations require separate verification.', ARRAY['1:1','4:5','16:9','9:16'],
   'SCHEDULED — CONNECTION REQUIRED', 'PROPOSED', ARRAY['linkedin','autumn-2026','mobility-operator']),

  ('b1600000-0000-4000-8000-000000000007', '30/9 — Det som belönas ska kunna följas upp', 'linkedin',
   'Explain CoreOS proof and measurement value.', 'Municipalities, operators, pilot owners and investors',
   'LinkedIn Höstserie 2026', 'linkedin', '4:5', 'Bygg piloten runt tydliga KPI:er från start',
   'utm_source=linkedin&utm_medium=organic&utm_campaign=autumn_2026&utm_content=measurement',
   E'Belöningar är enkla att prata om. Effekten är svårare.\n\nDärför bygger vi ParkKey™ runt verifierade händelser och tydlig uppföljning.\n\nI en pilot vill vi kunna se vad som faktiskt hänt: vilka definierade events som verifierats, hur belöningen används och vilka KPI:er som rör sig.\n\nCoreOS är vårt operativa lager för att hålla ihop pilot, uppföljning och bevis — utan att kalla mål för resultat.\n\nMät först. Skala sedan.\n\n#Data #CoreOS #Mobility #ParkKey',
   E'Rewards are easy to describe. Impact is harder. ParkKey is built around verified events and explicit follow-up.',
   'Mät först. Skala sedan.', 'VERIFIERAD HÄNDELSE → KPI → BESLUT',
   'Proof-first, no vanity metrics.', 'Parky should be minimal or absent; proof dominates.',
   'Nordic city and restrained CoreOS proof interface, premium dark cinematic treatment.',
   'CoreOS concept panels; ParkKey visual language; city mobility backdrop.',
   'Vertical 4:5 cinematic Nordic mobility scene with restrained CoreOS-style proof dashboard overlay, event verification and KPI framework without fabricated values, premium dark teal treatment, overlay: "Mät först. Skala sedan."',
   'No fabricated KPI values, no fake ROI, no fake CO2 savings, no crowded dashboard.',
   'Cinematisk stadsmiljö med ett återhållsamt CoreOS-lager för verifierade händelser och KPI-uppföljning.',
   'Any displayed figures must be EXAMPLE/TARGET unless sourced from verified production data.', ARRAY['1:1','4:5','16:9','9:16'],
   'SCHEDULED — CONNECTION REQUIRED', 'PROPOSED', ARRAY['linkedin','autumn-2026','coreos','measurement']),

  ('b1600000-0000-4000-8000-000000000008', '2/10 — Vilket beteende vill ni förändra?', 'linkedin',
   'End the series with a focused pilot conversation CTA.', 'Municipalities, mobility operators, destinations and property actors',
   'LinkedIn Höstserie 2026', 'linkedin', '4:5', 'Berätta vilket beteende ni vill förändra på parkkey.org',
   'utm_source=linkedin&utm_medium=organic&utm_campaign=autumn_2026&utm_content=pilot_invite',
   E'Om ni fick välja ett beteende att påverka de kommande 8–12 veckorna — vilket skulle det vara?\n\nFärre korta bilresor?\nFler som går sista biten?\nMer kollektivtrafik?\nBättre användning av parkering?\nMer lokal aktivitet?\n\nDet är där vi vill börja. Inte med en stor plattformspresentation, utan med ett konkret problem, en befintlig digital ingång och en pilot som går att mäta.\n\nSkriv gärna till mig eller besök parkkey.org.\n\n#ParkKey #Pilot #Mobility #SmartCity',
   E'If you could change one mobility behaviour over the next 8–12 weeks, which one would you choose?',
   'Vilket beteende vill ni förändra?', 'ETT BETEENDE. EN PILOT. ETT MÄTBART SVAR.',
   'Conversation CTA, specific and low-friction.', 'Canonical Parky may close the series beside the ParkKey logo.',
   'Warm Nordic autumn city closing frame, optimistic and credible.',
   'Canonical Parky; approved ParkKey logo; city mobility; one CTA.',
   'Vertical 4:5 cinematic Nordic autumn city, multiple real mobility choices visible naturally, canonical Parky exact reference near the ParkKey brand mark, premium optimistic closing frame, overlay: "Vilket beteende vill ni förändra?"',
   'No fake partner logos, no unverified statistics, no multiple CTAs, no redesigned Parky.',
   'Nordisk stad med flera mobilitetsval och en tydlig ParkKey-inbjudan till pilotdialog.',
   'Question/CTA only; no performance claim.', ARRAY['1:1','4:5','16:9','9:16'],
   'SCHEDULED — CONNECTION REQUIRED', 'PROPOSED', ARRAY['linkedin','autumn-2026','pilot','cta'])
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.social_post_assets (post_id, media_asset_id, sort_order, alt_text)
VALUES
 ('b1600000-0000-4000-8000-000000000001','a1600000-0000-4000-8000-000000000001',0,'Befintlig mobilitetsapp med ParkKey som belöningslager i nordisk höststad.'),
 ('b1600000-0000-4000-8000-000000000002','a1600000-0000-4000-8000-000000000002',0,'Parky markerar ett varmt belöningsögonblick efter en positiv aktivitet.'),
 ('b1600000-0000-4000-8000-000000000003','a1600000-0000-4000-8000-000000000003',0,'Verifierad parkeringshändelse leder vidare till nästa belönade aktivitet.'),
 ('b1600000-0000-4000-8000-000000000004','a1600000-0000-4000-8000-000000000004',0,'ParkKey-belöning kopplar verifierad aktivitet till lokalt värde.'),
 ('b1600000-0000-4000-8000-000000000005','a1600000-0000-4000-8000-000000000005',0,'Avgränsad ParkKey-pilot visualiserad i nordisk stadsmiljö.'),
 ('b1600000-0000-4000-8000-000000000006','a1600000-0000-4000-8000-000000000006',0,'Samma mobilitetsapp med ett tillagt ParkKey-belöningslager.'),
 ('b1600000-0000-4000-8000-000000000007','a1600000-0000-4000-8000-000000000007',0,'CoreOS-koncept visar verifierade events och KPI-ramverk utan fabricerade siffror.'),
 ('b1600000-0000-4000-8000-000000000008','a1600000-0000-4000-8000-000000000008',0,'Nordisk stad och Parky med inbjudan till en konkret pilotdialog.')
ON CONFLICT (post_id, media_asset_id) DO NOTHING;

INSERT INTO public.social_schedules
  (id, post_id, scheduled_at, timezone, status, notes)
VALUES
  ('c1600000-0000-4000-8000-000000000001','b1600000-0000-4000-8000-000000000001','2026-09-16T17:30:00+02:00','Europe/Stockholm','SCHEDULED — CONNECTION REQUIRED','Editorial schedule only. No PUBLISHED state without verified LinkedIn API post ID/URL.'),
  ('c1600000-0000-4000-8000-000000000002','b1600000-0000-4000-8000-000000000002','2026-09-18T08:15:00+02:00','Europe/Stockholm','SCHEDULED — CONNECTION REQUIRED','Editorial schedule only. Attach approved final asset before publish attempt.'),
  ('c1600000-0000-4000-8000-000000000003','b1600000-0000-4000-8000-000000000003','2026-09-21T08:15:00+02:00','Europe/Stockholm','SCHEDULED — CONNECTION REQUIRED','Editorial schedule only. Generic operator context unless co-branding is verified.'),
  ('c1600000-0000-4000-8000-000000000004','b1600000-0000-4000-8000-000000000004','2026-09-23T08:15:00+02:00','Europe/Stockholm','SCHEDULED — CONNECTION REQUIRED','Editorial schedule only. No invented merchant identity or offer.'),
  ('c1600000-0000-4000-8000-000000000005','b1600000-0000-4000-8000-000000000005','2026-09-25T08:15:00+02:00','Europe/Stockholm','SCHEDULED — CONNECTION REQUIRED','Editorial schedule only. Claims remain framework/proposed until verified.'),
  ('c1600000-0000-4000-8000-000000000006','b1600000-0000-4000-8000-000000000006','2026-09-28T08:15:00+02:00','Europe/Stockholm','SCHEDULED — CONNECTION REQUIRED','Editorial schedule only. No claim of named live integration.'),
  ('c1600000-0000-4000-8000-000000000007','b1600000-0000-4000-8000-000000000007','2026-09-30T08:15:00+02:00','Europe/Stockholm','SCHEDULED — CONNECTION REQUIRED','Editorial schedule only. KPI values require verified evidence.'),
  ('c1600000-0000-4000-8000-000000000008','b1600000-0000-4000-8000-000000000008','2026-10-02T08:15:00+02:00','Europe/Stockholm','SCHEDULED — CONNECTION REQUIRED','Editorial schedule only. Final publish requires approved asset and verified LinkedIn API response.')
ON CONFLICT (id) DO NOTHING;
