// This file is automatically generated. Do not edit it directly.
// Server-side Supabase admin client - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function firstSecretKeyFromJson(value: string | undefined): string | undefined {
  if (!value) return undefined;
  try {
    const parsed = JSON.parse(value) as Record<string, unknown>;
    const preferred = parsed["default"];
    if (typeof preferred === "string" && preferred.trim()) return preferred.trim();
    const fallback = Object.values(parsed).find(
      (candidate): candidate is string =>
        typeof candidate === "string" && candidate.trim().length > 0,
    );
    return fallback?.trim();
  } catch {
    return undefined;
  }
}

function getSupabaseAdminKey(): string | undefined {
  // Elevated access is server-only. Prefer Supabase's current secret-key format,
  // but allow the legacy service-role JWT for trusted scheduled Worker jobs.
  // Neither value may ever be exposed to VITE_* or client bundles.
  return (
    process.env["SUPABASE_SECRET_KEY"]?.trim() ||
    firstSecretKeyFromJson(process.env["SUPABASE_SECRET_KEYS"]) ||
    process.env["SUPABASE_SERVICE_ROLE_KEY"]?.trim() ||
    undefined
  );
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env["SUPABASE_URL"];
  const SUPABASE_ADMIN_KEY = getSupabaseAdminKey();

  if (!SUPABASE_URL || !SUPABASE_ADMIN_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_ADMIN_KEY
        ? ["SUPABASE_SECRET_KEY / SUPABASE_SECRET_KEYS / SUPABASE_SERVICE_ROLE_KEY"]
        : []),
    ];
    const message = `Missing Supabase server environment variable(s): ${missing.join(", ")}. Ensure the server runtime exposes a Supabase admin key.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ADMIN_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_ADMIN_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with elevated access - bypasses RLS.
// SECURITY: Only use this for trusted server-side operations, never expose to client code.
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
